### ISSUE TITLE
java.lang.ClassCastException: class java.math.BigInteger cannot be cast to class java.lang.String (Huisnummer)

### ISSUE THREAD

**Issue by SanderH** [SanderH/josm-ods-bag#1]
java.lang.ClassCastException: class java.math.BigInteger cannot be cast to class java.lang.String (java.math.BigInteger and java.lang.String are in module java.base of loader 'bootstrap')
	at org.openstreetmap.josm.plugins.ods.entities.opendata.FeatureUtil.getString(FeatureUtil.java:32)
	at org.openstreetmap.josm.plugins.ods.bag.factories.NL_GenericAddressFactory.createHouseNumber(NL_GenericAddressFactory.java:47)

**Comment by SanderH** [comment]
Lijkt erop dat https://geodata.nationaalgeoregister.nl/bag/wfs/v1_1?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType&TYPENAME=bag:verblijfsobject nu integer is ipv string
